services:
  core:
    build:
      context: ./core
      dockerfile: ./Dockerfile.dev
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      CORE_URI: ${CORE_URI}
    ports:
      - "8080:8000"
    volumes:
      - ./core:/app
  react:
    image: node:latest
    command: npm start
    working_dir: /app
    volumes:
      - "./gui:/app"
    ports:
      - "3000:3000"